### PR TITLE
Bug fixing and improvements for Neos 1.2

### PR DESCRIPTION
**Pull request by davidspiola**
Hi Dominique,
my first fork and pull request on github. Please let me know if I did something wrong!

bests,
David

### CODE REVIEW

**Comment by dfeyer** [comment]
Can you split this PR ? I'm ok with the bugfix, and that can be merged.

But the feature need to be discussed ... I'm not sure if separated file really help the user. Schema for schema.org use a lots of dependencies, so i feel that is a developer need a schema, per ex. Person, it's more useful to have all the dependencies in the same file.

**Comment by davidspiola** [comment]
It's actually quite helpful if you would like to use additional types you didn't think of. You don't have to start from scratch every time you add types. Let's say you generated a 'person', and then you realize you need a 'hotel' as well. You would have to delete the nodeType definition and start again. With separate files it will generate the missing types in the data folder and you just copy it to your site package. This works quite well! From my point of view dependencies are not corrupted. 

I'll separate the commits in two PR, but I agree that we should discuss further steps. I have some suggestions and short hands based on using the package I would like to share with you. I'm working on some concepts but I'm not 100% sure if I'm heading in the right direction.

**Comment by dfeyer** [comment]
Thanks, maybe we can organize a small meeting during Inspiring Conference if your are there.

**Comment by davidspiola** [comment]
Sure... let's do that!

**Pull request closed without merging**
